version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lotspace-postgres-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      context: .
    container_name: lotspace
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: postgres://postgres:postgres@db:5432/mydb
    ports:
      - "3000:3000"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: lotspace-pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
