export enum CommonErrorCodes {
    NO_DATA_WAS_FOUND = 'NO_DATA_WAS_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED'
}
