export default {
    "id": 9,
    "ABS": "",
    "ActiveSafetySysNote": "",
    "AdaptiveCruiseControl": "",
    "AdaptiveDrivingBeam": "",
    "AdaptiveHeadlights": "",
    "AdditionalErrorText": "",
    "AirBagLocCurtain": "1st Row (Driver and Passenger)",
    "AirBagLocFront": "1st Row (Driver and Passenger)",
    "AirBagLocKnee": "1st Row (Driver and Passenger)",
    "AirBagLocSeatCushion": "",
    "AirBagLocSide": "1st Row (Driver and Passenger)",
    "AutoReverseSystem": "",
    "AutomaticPedestrianAlertingSound": "",
    "AxleConfiguration": "",
    "Axles": "",
    "BasePrice": "",
    "BatteryA": "",
    "BatteryA_to": "",
    "BatteryCells": "",
    "BatteryInfo": "",
    "BatteryKWh": "",
    "BatteryKWh_to": "",
    "BatteryModules": "",
    "BatteryPacks": "",
    "BatteryType": "",
    "BatteryV": "",
    "BatteryV_to": "",
    "BedLengthIN": "",
    "BedType": "Not Applicable",
    "BlindSpotIntervention": "",
    "BlindSpotMon": "",
    "BodyCabType": "Not Applicable",
    "BodyClass": "Coupe",
    "BrakeSystemDesc": "",
    "BrakeSystemType": "",
    "BusFloorConfigType": "Not Applicable",
    "BusLength": "",
    "BusType": "Not Applicable",
    "CAN_AACN": "",
    "CIB": "",
    "CashForClunkers": "",
    "ChargerLevel": "",
    "ChargerPowerKW": "",
    "CombinedBrakingSystem": "",
    "CoolingType": "",
    "CurbWeightLB": "",
    "CustomMotorcycleType": "Not Applicable",
    "DaytimeRunningLight": "",
    "DestinationMarket": "",
    "DisplacementCC": "1984",
    "DisplacementCI": "121.071108283",
    "DisplacementL": "1.984000",
    "Doors": "2",
    "DriveType": "AWD/All-Wheel Drive",
    "DriverAssist": "",
    "DynamicBrakeSupport": "",
    "EDR": "",
    "ESC": "",
    "EVDriveUnit": "",
    "ElectrificationLevel": "",
    "EngineConfiguration": "",
    "EngineCycles": "",
    "EngineCylinders": "4",
    "EngineHP": "220",
    "EngineHP_to": "",
    "EngineKW": "",
    "EngineManufacturer": "Audi",
    "EngineModel": "Flex Fuel Engine",
    "EntertainmentSystem": "",
    "ErrorCode": "0",
    "ErrorText": "0 - VIN decoded clean. Check Digit (9th position) is correct",
    "ForwardCollisionWarning": "",
    "FuelInjectionType": "",
    "FuelTankMaterial": "",
    "FuelTankType": "",
    "FuelTypePrimary": "Gasoline",
    "FuelTypeSecondary": "Ethanol (E85)",
    "GCWR": "",
    "GCWR_to": "",
    "GVWR": "Class 1: 6,000 lb or less (2,722 kg or less)",
    "GVWR_to": "Class 1: 6,000 lb or less (2,722 kg or less)",
    "KeylessIgnition": "",
    "LaneCenteringAssistance": "",
    "LaneDepartureWarning": "",
    "LaneKeepSystem": "",
    "LowerBeamHeadlampLightSource": "",
    "Make": "AUDI",
    "MakeID": "582",
    "Manufacturer": "AUDI AG",
    "ManufacturerId": "1149",
    "Model": "A5",
    "ModelID": "3787",
    "ModelYear": "2014",
    "MotorcycleChassisType": "Not Applicable",
    "MotorcycleSuspensionType": "Not Applicable",
    "NCSABodyType": "2-door sedan,hardtop,coupe",
    "NCSAMake": "Audi",
    "NCSAMapExcApprovedBy": "",
    "NCSAMapExcApprovedOn": "",
    "NCSAMappingException": "",
    "NCSAModel": "A5",
    "NCSANote": "",
    "NonLandUse": "",
    "Note": "",
    "OtherBusInfo": "",
    "OtherEngineInfo": "Fuel: GAS (50-St); Federal / California Emission Standard: BIN 5 / ULEV II; Emissions Certification Test Group: EADXV02.03UB, EADXJ02.0FUB (E85)",
    "OtherMotorcycleInfo": "",
    "OtherRestraintSystemInfo": "Restraint System: Side AirBags Front, Side Guard Air Curtain, Knee Airbags Front",
    "OtherTrailerInfo": "",
    "ParkAssist": "",
    "PedestrianAutomaticEmergencyBraking": "",
    "PlantCompanyName": "",
    "PlantCountry": "GERMANY",
    "PlantState": "",
    "PossibleValues": "",
    "Pretensioner": "",
    "RearAutomaticEmergencyBraking": "",
    "RearCrossTrafficAlert": "",
    "RearVisibilitySystem": "",
    "SAEAutomationLevel": "",
    "SAEAutomationLevel_to": "",
    "SeatBeltsAll": "",
    "SeatRows": "",
    "Seats": "",
    "SemiautomaticHeadlampBeamSwitching": "",
    "Series": "",
    "Series2": "",
    "SteeringLocation": "",
    "SuggestedVIN": "",
    "TPMS": "Indirect",
    "TopSpeedMPH": "",
    "TrackWidth": "",
    "TractionControl": "",
    "TrailerBodyType": "Not Applicable",
    "TrailerLength": "",
    "TrailerType": "Not Applicable",
    "TransmissionSpeeds": "",
    "TransmissionStyle": "Automatic",
    "Trim": "quattro Premium",
    "Trim2": "",
    "Turbo": "",
    "VIN": "WAUCFAFR0EA052668",
    "ValveTrainDesign": "",
    "VehicleDescriptor": "WAUCFAFR*EA",
    "VehicleType": "PASSENGER CAR",
    "WheelBaseLong": "",
    "WheelBaseShort": "",
    "WheelBaseType": "",
    "WheelSizeFront": "",
    "WheelSizeRear": "",
    "WheelieMitigation": "",
    "Wheels": "",
    "Windows": ""
}